### ISSUE TITLE
With a Nvidia 390 driver applet shows invalid "On-Demand" option.

### ISSUE THREAD

**Issue by timboxyz** [linuxmint/nvidia-prime-applet#17]
The "On-Demand" mode is not valid for this driver and selecting the option leads to an unusable desktop after performing the requested reboot (no taskbar, no icons, no cursor, no right click context menu and desktop BG image zoomed in compared to normal).

Please see the thread at:-

[https://github.com/linuxmint/nvidia-prime-applet/issues/17](https://forums.linuxmint.com/viewtopic.php?f=59&t=387005)

which includes HW info and `dpkg -l | grep -i nvidia` dump, as well as screen shots of menu options offered.

**Comment by clefebvre** [comment]
In a terminal, run `/usr/lib/nvidia-prime-applet/nvidia-prime`.

Paste the output here.

**Comment by timboxyz** [comment]
```
Detected Intel GPU: 8086:0116;0000:00:02:0;1
Detected NVIDIA GPU: 10de:0df4;0000:01:00:0;0
Required nvidia driver version for on-demand: 435.17
Detected nvidia driver version: 390.157

(nvidia-prime:7878): XApp-WARNING **: 12:00:38.415: XAppStatusIcon: lost or could not acquire presence on dbus.  Refreshing.
```
then it hung

**Comment by mtwebster** [comment]
This wouldn't be related to this applet if you're able to (attempt to) switch to on-demand via Nvidia's settings app

Can you try a couple of things - 

- Uninstall your nvidia drivers via the driver manager (switch to nouveau), reboot.
- Check if the file 'requires_offloading' exists in `/var/lib/ubuntu-drivers-common`. Delete it, then run `apt install --reinstall ubuntu-drivers-common`
- Reinstall the nvidia driver, reboot again.

**Comment by clefebvre** [comment]
The code fails here imo..

![image](https://github.com/linuxmint/nvidia-prime-applet/assets/1138515/3cf3997f-7b4f-435d-8896-06b34b11f73a)

**Comment by clefebvre** [comment]
Required nvidia driver version for on-demand: 435.17
Detected nvidia driver version: 390.157

if 390.157 < 435.17, it should print "On-demand not available".

**Comment by clefebvre** [comment]
We probably need this:

`current_version = version.parse(current_version)`

**Comment by mtwebster** [comment]
The commit 949ae8ce9ec fixes the version check for the nvidia tray applet *only*, preventing it from displaying that option.

If you're able to switch to on-demand using Nvidia Settings (which is maintained by Nvidia, not Mint), there's probably something configured wrong on your machine. See the troubleshooting steps I posted above.
