### ISSUE TITLE
Redesign the icon of "nvidia-prime-applet".

### ISSUE THREAD

**Issue by kacperpaczos** [linuxmint/nvidia-prime-applet#18]
The Intel icon is too small; we should change it to something eye-catching, with a prominent blue color. If the Nvidia mode is enabled, it should be represented by a green Nvidia icon. Additionally, the icon should have a more square shape, similar to other icons.

![image](https://github.com/linuxmint/nvidia-prime-applet/assets/23406555/6640a0f5-3726-41b7-b15a-5664fe96011f)

**Comment by clefebvre** [comment]
That's subjective I guess. We opted for symbolic icons since we didn't want to catch the user's attention and the icon was always visible.
